/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSiteSlugRouteImport } from './routes/s.$siteSlug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AppSitesRouteImport } from './routes/app.sites'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppFormularioRouteImport } from './routes/app.formulario'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as SSiteSlugPageSlugRouteImport } from './routes/s.$siteSlug.$pageSlug'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'
import { Route as ApiPublicCalendlyWebhookRouteImport } from './routes/api/public/calendly-webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugRoute = SSiteSlugRouteImport.update({
  id: '/s/$siteSlug',
  path: '/s/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppFormularioRoute = AppFormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const SSiteSlugPageSlugRoute = SSiteSlugPageSlugRouteImport.update({
  id: '/$pageSlug',
  path: '/$pageSlug',
  getParentRoute: () => SSiteSlugRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AppSitesRoute,
} as any)
const ApiPublicCalendlyWebhookRoute =
  ApiPublicCalendlyWebhookRouteImport.update({
    id: '/api/public/calendly-webhook',
    path: '/api/public/calendly-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/formulario': typeof AppFormularioRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sites': typeof AppSitesRouteWithChildren
  '/f/$slug': typeof FSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRouteWithChildren
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/s/$siteSlug/$pageSlug': typeof SSiteSlugPageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/formulario': typeof AppFormularioRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sites': typeof AppSitesRouteWithChildren
  '/f/$slug': typeof FSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRouteWithChildren
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/s/$siteSlug/$pageSlug': typeof SSiteSlugPageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/formulario': typeof AppFormularioRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sites': typeof AppSitesRouteWithChildren
  '/f/$slug': typeof FSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRouteWithChildren
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/s/$siteSlug/$pageSlug': typeof SSiteSlugPageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/agendamentos'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/formulario'
    | '/app/pipeline'
    | '/app/sites'
    | '/f/$slug'
    | '/s/$siteSlug'
    | '/api/public/calendly-webhook'
    | '/app/sites/$siteId'
    | '/s/$siteSlug/$pageSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/agendamentos'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/formulario'
    | '/app/pipeline'
    | '/app/sites'
    | '/f/$slug'
    | '/s/$siteSlug'
    | '/api/public/calendly-webhook'
    | '/app/sites/$siteId'
    | '/s/$siteSlug/$pageSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/agendamentos'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/formulario'
    | '/app/pipeline'
    | '/app/sites'
    | '/f/$slug'
    | '/s/$siteSlug'
    | '/api/public/calendly-webhook'
    | '/app/sites/$siteId'
    | '/s/$siteSlug/$pageSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  FSlugRoute: typeof FSlugRoute
  SSiteSlugRoute: typeof SSiteSlugRouteWithChildren
  ApiPublicCalendlyWebhookRoute: typeof ApiPublicCalendlyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug': {
      id: '/s/$siteSlug'
      path: '/s/$siteSlug'
      fullPath: '/s/$siteSlug'
      preLoaderRoute: typeof SSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/formulario': {
      id: '/app/formulario'
      path: '/formulario'
      fullPath: '/app/formulario'
      preLoaderRoute: typeof AppFormularioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$siteSlug/$pageSlug': {
      id: '/s/$siteSlug/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/s/$siteSlug/$pageSlug'
      preLoaderRoute: typeof SSiteSlugPageSlugRouteImport
      parentRoute: typeof SSiteSlugRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppSitesRoute
    }
    '/api/public/calendly-webhook': {
      id: '/api/public/calendly-webhook'
      path: '/api/public/calendly-webhook'
      fullPath: '/api/public/calendly-webhook'
      preLoaderRoute: typeof ApiPublicCalendlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSitesRouteChildren {
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
}

const AppSitesRouteChildren: AppSitesRouteChildren = {
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
}

const AppSitesRouteWithChildren = AppSitesRoute._addFileChildren(
  AppSitesRouteChildren,
)

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormularioRoute: typeof AppFormularioRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSitesRoute: typeof AppSitesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFormularioRoute: AppFormularioRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSitesRoute: AppSitesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SSiteSlugRouteChildren {
  SSiteSlugPageSlugRoute: typeof SSiteSlugPageSlugRoute
}

const SSiteSlugRouteChildren: SSiteSlugRouteChildren = {
  SSiteSlugPageSlugRoute: SSiteSlugPageSlugRoute,
}

const SSiteSlugRouteWithChildren = SSiteSlugRoute._addFileChildren(
  SSiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  FSlugRoute: FSlugRoute,
  SSiteSlugRoute: SSiteSlugRouteWithChildren,
  ApiPublicCalendlyWebhookRoute: ApiPublicCalendlyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
