ALTER TABLE public.pages
  ADD COLUMN IF NOT EXISTS freeform BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS canvas_height INTEGER NOT NULL DEFAULT 1200;

ALTER TABLE public.blocks
  ADD COLUMN IF NOT EXISTS x INTEGER,
  ADD COLUMN IF NOT EXISTS y INTEGER,
  ADD COLUMN IF NOT EXISTS w INTEGER,
  ADD COLUMN IF NOT EXISTS h INTEGER,
  ADD COLUMN IF NOT EXISTS rotation REAL NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS z_index INTEGER NOT NULL DEFAULT 0;